import { useState } from 'react';
import { ArrowUpRight, Bell, CalendarDays, Check, ChevronDown, CirclePlus, Clock3, Command, Layers3, MoreHorizontal, Plus, Search, Sparkles, Target, Zap } from 'lucide-react';

const projects = [
  { name: 'Orbit website', progress: 74, color: 'bg-violet-400', members: ['AM', 'LK', 'YN'] },
  { name: 'Field notes', progress: 46, color: 'bg-amber-300', members: ['JR', 'SK'] },
  { name: 'Noma launch', progress: 91, color: 'bg-cyan-300', members: ['SP', 'MB', 'DT'] },
];
const initialTasks = [
  { title: 'Map the onboarding flow', tag: 'Design', time: '10:00', done: true },
  { title: 'Prepare the client walkthrough', tag: 'Review', time: '13:30', done: false },
  { title: 'Write the launch update', tag: 'Writing', time: '16:00', done: false },
];

export default function App() {
  const [tasks, setTasks] = useState(initialTasks);
  const [notice, setNotice] = useState('');
  const completed = tasks.filter((task) => task.done).length;
  const toggleTask = (index) => setTasks((current) => current.map((task, taskIndex) => taskIndex === index ? { ...task, done: !task.done } : task));
  const addTask = () => { setTasks((current) => [...current, { title: 'Sketch a new bright idea', tag: 'Personal', time: 'Tomorrow', done: false }]); setNotice('A fresh task was added to your day.'); window.setTimeout(() => setNotice(''), 2600); };

  return <div className="min-h-screen overflow-hidden px-4 py-5 text-slate-950 sm:px-8 lg:px-12">
    <div className="liquid-background" aria-hidden="true"><i /><i /><i /></div>
    <div className="mx-auto max-w-7xl">
      <header className="glass-panel flex items-center justify-between rounded-[28px] px-5 py-3.5 sm:px-7">
        <div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-slate-950 text-white shadow-lg"><Sparkles size={19} /></div><span className="text-lg font-semibold tracking-tight">Luma</span><span className="hidden rounded-full bg-white/45 px-3 py-1 text-xs font-medium text-slate-600 sm:block">Personal space</span></div>
        <nav className="hidden items-center gap-7 text-sm font-medium text-slate-600 md:flex"><a className="text-slate-950" href="#today">Today</a><a href="#projects">Projects</a><a href="#insights">Insights</a></nav>
        <div className="flex items-center gap-2"><button className="glass-button grid h-10 w-10 place-items-center rounded-xl" aria-label="Search"><Search size={18} /></button><button className="glass-button grid h-10 w-10 place-items-center rounded-xl" aria-label="Notifications"><Bell size={18} /></button><button className="ml-1 h-10 w-10 rounded-xl bg-gradient-to-br from-fuchsia-500 via-rose-400 to-amber-300 text-xs font-bold text-white shadow-md">YK</button></div>
      </header>
      <main className="grid gap-5 py-5 lg:grid-cols-[1.45fr_.85fr]">
        <section className="glass-panel rounded-[32px] p-6 sm:p-9" id="today">
          <div className="flex items-start justify-between"><div><p className="mb-3 flex items-center gap-2 text-sm font-medium text-slate-600"><span className="h-2 w-2 rounded-full bg-emerald-500" /> Tuesday, 8 September</p><h1 className="max-w-xl text-4xl font-semibold leading-[1.05] tracking-[-0.055em] sm:text-6xl">Make room for <span className="text-gradient">what matters.</span></h1></div><button className="glass-button hidden h-11 items-center gap-2 rounded-2xl px-4 text-sm font-semibold sm:flex"><CalendarDays size={17} /> September <ChevronDown size={15} /></button></div>
          <div className="mt-9 grid gap-3 sm:grid-cols-3"><Stat icon={<Target size={19} />} label="Weekly focus" value="72%" detail="+8% from last week" color="bg-violet-100 text-violet-700" /><Stat icon={<Clock3 size={19} />} label="Deep work" value="4h 20m" detail="Your best rhythm" color="bg-cyan-100 text-cyan-700" /><Stat icon={<Zap size={19} />} label="Momentum" value="Great" detail="3-day streak" color="bg-amber-100 text-amber-700" /></div>
          <div className="mt-8 rounded-[26px] border border-white/60 bg-white/30 p-4 sm:p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">Today&apos;s flow</h2><p className="mt-0.5 text-sm text-slate-500">{completed} of {tasks.length} intentions complete</p></div><span className="rounded-full bg-slate-950 px-3 py-1.5 text-xs font-semibold text-white">{Math.round((completed / tasks.length) * 100)}%</span></div><div className="space-y-2">{tasks.map((task, index) => <button onClick={() => toggleTask(index)} key={`${task.title}-${index}`} className="group flex w-full items-center gap-3 rounded-2xl bg-white/55 p-3 text-left transition hover:-translate-y-0.5 hover:bg-white/85"><span className={`grid h-7 w-7 shrink-0 place-items-center rounded-full border-2 ${task.done ? 'border-emerald-500 bg-emerald-500 text-white' : 'border-slate-300 bg-white text-transparent'}`}><Check size={15} strokeWidth={3} /></span><span className={`flex-1 text-sm font-medium ${task.done ? 'text-slate-400 line-through' : 'text-slate-800'}`}>{task.title}</span><span className="hidden rounded-lg bg-slate-100 px-2 py-1 text-xs text-slate-500 sm:block">{task.tag}</span><span className="text-xs font-medium text-slate-400">{task.time}</span></button>)}</div><button onClick={addTask} className="mt-3 flex items-center gap-2 px-2 py-2 text-sm font-semibold text-slate-600 transition hover:text-slate-950"><CirclePlus size={18} /> Add an intention</button></div>
        </section>
        <aside className="space-y-5"><section className="glass-panel rounded-[32px] p-6"><div className="flex items-center justify-between"><div><p className="text-sm text-slate-500">Your energy</p><h2 className="mt-1 text-2xl font-semibold tracking-tight">A calm, clear day</h2></div><div className="grid h-12 w-12 place-items-center rounded-2xl bg-gradient-to-br from-amber-200 to-rose-300 text-xl shadow-sm">☀️</div></div><div className="mt-7 flex items-end gap-2">{[36, 52, 43, 72, 62, 90, 77].map((height, index) => <div key={height} className="flex-1"><div className={`rounded-full ${index === 5 ? 'bg-gradient-to-t from-fuchsia-500 to-rose-300' : 'bg-slate-950/10'}`} style={{ height }} /></div>)}</div><div className="mt-3 flex justify-between text-[11px] font-medium text-slate-400"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></section>
          <section className="glass-panel rounded-[32px] p-6" id="projects"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Layers3 size={19} /><h2 className="font-semibold">Active projects</h2></div><button className="glass-button grid h-8 w-8 place-items-center rounded-xl" aria-label="Add project"><Plus size={16} /></button></div><div className="mt-4 space-y-3">{projects.map((project) => <div key={project.name} className="rounded-2xl bg-white/45 p-3.5"><div className="flex items-center justify-between"><span className="text-sm font-semibold">{project.name}</span><MoreHorizontal size={17} className="text-slate-400" /></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-950/10"><div className={`h-full rounded-full ${project.color}`} style={{ width: `${project.progress}%` }} /></div><div className="mt-3 flex items-center justify-between"><div className="flex -space-x-2">{project.members.map((member, index) => <span key={member} className="grid h-6 w-6 place-items-center rounded-full border-2 border-white text-[8px] font-bold" style={{ backgroundColor: ['#fbcfe8', '#bfdbfe', '#bbf7d0'][index] }}>{member}</span>)}</div><span className="text-xs font-medium text-slate-500">{project.progress}%</span></div></div>)}</div><button className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl py-2 text-sm font-semibold text-slate-600 hover:bg-white/35">See all projects <ArrowUpRight size={15} /></button></section></aside>
      </main>
      <section id="insights" className="glass-panel mb-3 flex flex-col justify-between gap-4 rounded-[26px] px-6 py-5 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-white/50 text-slate-700"><Command size={19} /></div><div><p className="font-semibold">A little nudge from Luma</p><p className="text-sm text-slate-500">Your clearest thinking happens before 11:30. Protect that window.</p></div></div><button className="glass-button whitespace-nowrap rounded-xl px-4 py-2 text-sm font-semibold">Plan my focus</button></section>
    </div>{notice && <div className="fixed bottom-6 left-1/2 -translate-x-1/2 rounded-2xl bg-slate-950 px-5 py-3 text-sm font-medium text-white shadow-2xl">{notice}</div>}</div>;
}
function Stat({ icon, label, value, detail, color }) { return <div className="rounded-2xl bg-white/35 p-4"><div className={`grid h-9 w-9 place-items-center rounded-xl ${color}`}>{icon}</div><p className="mt-4 text-xs font-medium text-slate-500">{label}</p><p className="mt-0.5 text-xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-[11px] text-slate-500">{detail}</p></div>; }
